# Generated by Django 4.1.9 on 2023-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
