# Generated by Django 4.1.9 on 2023-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='redirect',
            field=models.BooleanField(blank=True, default=False, verbose_name='Редирект'),
        ),
    ]
